package com.seven.asimov.test.tool.tests.device.certification.resources;

public class StabilityTopResources {
    public static final String[] topHttpResources = {"http://google.com", "http://facebook.com", "http://youtube.com",
            "http://yahoo.com", "http://baidu.com", "http://wikipedia.org",
            "http://live.com", "http://twitter.com", "http://qq.com",
            "http://amazon.com", "http://blogspot.com", "http://linkedin.com",
            "http://google.co.in", "http://taobao.com", "http://sina.com.cn",
            "http://yahoo.co.jp", "http://msn.com", "http://wordpress.com",
            "http://google.com.hk", "http://google.de", "http://t.co",
            "http://ebay.com",/*"http://googleusercontent.com",*/"http://google.co.uk",
            "http://google.co.jp", "http://yandex.ru", "http://163.com",
            "http://google.fr", "http://weibo.com", "http://bing.com",
            "http://microsoft.com", "http://google.com.br", "http://soso.com",
            "http://mail.ru", "http://tumblr.com", "http://pinterest.com",
            "http://paypal.com", "http://apple.com", "http://google.it",
            "http://vk.com", "http://babylon.com", "http://google.ru",
            "http://google.es", "http://blogger.com", "http://sohu.com",
            "http://craigslist.org", "http://imdb.com", "http://flickr.com",
            "http://bbc.co.uk", "http://tudou.com", "http://xvideos.com",
            "http://fc2.com", "http://ifeng.com", "http://go.com",
            "http://xhamster.com", "http://ask.com", "http://youku.com",
            "http://livejasmin.com", "http://google.com.mx", "http://google.ca",
            "http://tmall.com", "http://zedo.com", "http://conduit.com",
            "http://imgur.com", "http://odnoklassniki.ru", "http://cnn.com",
            "http://google.co.id", "http://pornhub.com",/*"http://hao123.com",*/
            "http://adobe.com", "http://aol.com", "http://mediafire.com",
            "http://thepiratebay.se", "http://espn.go.com", "http://alibaba.com",
            "http://google.com.tr", "http://ebay.de", "http://avg.com",
            "http://rakuten.co.jp", "http://google.com.au", "http://about.com",
            "http://blogspot.in", "http://chinaz.com", "http://wordpress.org",
            "http://ameblo.jp", "http://ebay.co.uk", "http://alipay.com",
            "http://godaddy.com", "http://uol.com.br", "http://amazon.de",
            "http://google.pl", "http://360buy.com", "http://amazon.co.jp",
            "http://renren.com", "http://stackoverflow.com", "http://huffingtonpost.com",
            /*"http://bp.blogspot.com",*/"http://4shared.com", "http://adf.ly",
            "http://cnet.com", "http://youporn.com", "http://netflix.com",
            "http://dailymotion.com", "http://globo.com", "http://livedoor.com",
            "http://douban.com", "http://redtube.com", "http://sogou.com",
            "http://nytimes.com", "http://amazon.co.uk", "http://google.nl",
            "http://google.com.sa", "http://vimeo.com", "http://livejournal.com",
            "http://badoo.com", "http://cnzz.com", "http://weather.com",
            "http://google.com.ar", "http://torrentz.eu", "http://secureserver.net",
            "http://reddit.com", "http://xnxx.com",/*"http://yieldmanager.com",*/
            "http://ehow.com",/*"http://addthis.com",*/"http://mywebsearch.com",
            "http://dailymail.co.uk", "http://tianya.cn", "http://bankofamerica.com",
            "http://pengyou.com", "http://tube8.com", "http://deviantart.com",
            "http://wigetmedia.com", "http://aweber.com", "http://google.com.pk",
            "http://goo.ne.jp", "http://searchnu.com", "http://indiatimes.com",
            "http://search-results.com", "http://google.co.th", "http://sparkstudios.com",
            /*"http://warriorforum.com",*/"http://answers.com", "http://clicksor.com",
            "http://google.cn", "http://58.com", "http://mozilla.org",
            "http://google.com.eg", "http://dropbox.com", "http://naver.com",
            "http://google.co.za", "http://kat.ph", "http://sourceforge.net",
            "http://chase.com", "http://pconline.com.cn", "http://stumbleupon.com",
            "http://360.cn"/*"http://photobucket.com"*/,/*"http://myspace.com",*/
            "http://filestube.com",/*"http://amazonaws.com",*/"http://instagr.am",
            "http://blogfa.com", "http://56.com", "http://etsy.com",
            "http://spiegel.de", "http://xunlei.com", "http://wikia.com",
            "http://wikimedia.org", "http://espncricinfo.com", "http://statcounter.com",
            "http://skype.com", "http://google.com.my", "http://adcash.com",
            "http://reference.com", "http://yesky.com", "http://slideshare.net",
            "http://google.co.ve", "http://booking.com", "http://doubleclick.com",
            "http://rapidshare.com", "http://fiverr.com", "http://ucoz.ru",
            "http://mgid.com", "http://zol.com.cn", "http://yelp.com",
            "http://walmart.com", "http://depositfiles.com", "http://wellsfargo.com",
            "http://digg.com", "http://foxnews.com", "http://outbrain.com",
            /*"http://zeekrewards.com",*/"http://guardian.co.uk", "http://google.com.co",
            "http://hootsuite.com", "http://adultfriendfinder.com", "http://liveinternet.ru",
            "http://download.com", "http://onet.pl", "http://comcast.net",
            "http://optmd.com", "http://bild.de", "http://taringa.net",
            "http://allegro.pl", "http://files.wordpress.com", "http://rediff.com",
            "http://nicovideo.jp", "http://google.gr", "http://google.be",
            "http://fbcdn.net", "http://softonic.com", "http://w3schools.com",
            "http://themeforest.net", "http://squidoo.com", "http://imageshack.us",
            "http://google.com.tw", "http://isohunt.com", "http://google.com.vn",
            "http://free.fr", "http://domaintools.com", "http://youjizz.com",
            "http://battle.net", "http://terra.com.br", "http://soku.com",
            "http://scribd.com", "http://y8.com", "http://archive.org",
            "http://hulu.com", "http://wsj.com", "http://leboncoin.fr",
            "http://google.com.ua", "http://xinhuanet.com",/*"http://blogspot.com.es",*/
            "http://ameba.jp", "http://rambler.ru", "http://iqiyi.com",
            "http://google.se", "http://hostgator.com", "http://nba.com",
            "http://9gag.com", "http://aizhan.com", "http://php.net",
            "http://salesforce.com", "http://repubblica.it", "http://google.at",
            "http://google.ro", "http://amazon.cn", "http://wordreference.com",
            "http://csdn.net", "http://hudong.com", "http://tripadvisor.com",
            "http://it168.com", "http://cam4.com", "http://orange.fr",
            "http://reuters.com", "http://clickbank.com", "http://google.com.ph",
            "http://tribalfusion.com", "http://ups.com", "http://hatena.ne.jp",
            "http://kaskus.us",/*"http://media.tumblr.com",*/"http://marca.com",
            "http://forbes.com", "http://rutracker.org", "http://telegraph.co.uk",
            "http://people.com.cn", "http://youdao.com", "http://google.cl",
            "http://linkwithin.com", "http://mashable.com", "http://51.la",
            "http://google.com.pe", "http://web.de", "http://samsung.com",
            "http://gmx.net", "http://daum.net", "http://china.com",
            "http://libero.it", "http://hardsextube.com", "http://xing.com",
            "http://wp.pl", "http://tagged.com", "http://sweetim.com",
            "http://paipai.com", "http://typepad.com", "http://thefreedictionary.com",
            "http://mixi.jp", "http://google.com.sg", "http://hp.com",
            "http://pandora.com", "http://ganji.com", "http://goal.com",
            "http://drtuber.com", "http://letv.com", "http://indeed.com",
            "http://angege.com", "http://blogspot.co.uk", "http://google.ch",
            "http://google.com.ng", "http://hubpages.com", "http://homeway.com.cn",
            "http://ikea.com", "http://soundcloud.com", "http://soufun.com",
            "http://kooora.com", "http://pof.com", "http://constantcontact.com",
            "http://letitbit.net", "http://ezinearticles.com", "http://xcar.com.cn",
            "http://narod.ru", "http://groupon.com", "http://google.pt",
            "http://socialcam.com", "http://target.com", "http://4399.com",
            "http://blogspot.it", "http://cj.com", "http://mlb.com",
            "http://blogspot.jp", "http://digitalpoint.com", "http://alimama.com",
            "http://ebay.it", "http://joomla.org", "http://orkut.com",
            "http://xe.com", "http://bitauto.com", "http://justbeenpaid.com",
            "http://kaixin001.com", "http://mercadolivre.com.br", "http://dell.com",
            "http://lemonde.fr", "http://uploaded.to", "http://maktoob.com",
            "http://weebly.com", "http://usps.com", "http://126.com",
            "http://putlocker.com", "http://ku6.com", "http://washingtonpost.com",
            "http://bestbuy.com", "http://corriere.it", "http://orkut.com.br",
            "http://freelancer.com", "http://shutterstock.com", "http://americanexpress.com",
            "http://kakaku.com", "http://ign.com", "http://match.com",
            "http://istockphoto.com", "http://blogspot.de",/*"http://seesaa.net",*/
            "http://mop.com",/*"http://ig.com.br",*/"http://51job.com",
            "http://github.com", "http://t-online.de", "http://over-blog.com",
            "http://google.ie", "http://elpais.com", "http://10086.cn",
            "http://nifty.com", "http://admin5.com", "http://techcrunch.com",
            "http://cntv.cn", "http://twitpic.com", "http://pchome.net",
            "http://seomoz.org", "http://leo.org", "http://bet365.com",
            "http://nih.gov", "http://ebay.com.au",/*"http://pptv.com",*/
            "http://att.com", "http://ning.com", "http://vancl.com",
            "http://zimbio.com", "http://detik.com", "http://in.com",
            "http://google.dz", "http://autohome.com.cn",/*"http://akamaihd.net",*/
            "http://bloomberg.com", "http://blogspot.fr", "http://seznam.cz",
            "http://elmundo.es",/*"http://trekaklik.com",*/"http://ero-advertising.com",
            /*"http://milliyet.com.tr",*/"http://infusionsoft.com", "http://dianping.com",
            "http://expedia.com", "http://google.ae", "http://w3.org",
            "http://twoo.com", "http://2ch.net", "http://google.co.hu",
            "http://gazeta.pl", "http://google.dk",/*"http://uimserv.net",*/
            "http://hurriyet.com.tr", "http://rapidgator.net", "http://sergey-mavrodi.com",
            "http://webs.com", "http://google.no", "http://google.cz",
            "http://usatoday.com", "http://extratorrent.com", "http://abcnews.go.com",
            "http://bluehost.com", "http://2345.com", "http://latimes.com",
            "http://mailchimp.com", "http://fedex.com", "http://metacafe.com",
            "http://huanqiu.com", "http://aliexpress.com", "http://39.net",
            "http://vnexpress.net", "http://mihanblog.com", "http://ilivid.com",
            /*"http://amazon.fr",*/"http://surveymonkey.com", "http://mynet.com",
            "http://ebay.fr", "http://google.co.il",/*"http://twimg.com",*/
            "http://warriorplus.com", "http://histats.com", "http://gsmarena.com",
            "http://speedtest.net", "http://dianxin.cn", "http://wretch.cc",
            /*"http://arpg2.com",*/"http://google.co.kr",/*"http://777wyx.com",*/
            "http://informer.com", "http://chinanews.com", "http://irctc.co.in",
            /*"http://peyvandha.ir",*/"http://drudgereport.com", "http://lefigaro.fr",
            "http://shaadi.com", "http://sakura.ne.jp", "http://flipkart.com",
            "http://rr.com", "http://newegg.com", "http://analyrics.com",
            "http://jobrapido.com", "http://meetup.com", "http://delicious.com",
            "http://drupal.org", "http://tmz.com", "http://enet.com.cn",
            "http://pcauto.com.cn", "http://movie2k.to", "http://turbobit.net",
            "http://bitly.com", "http://commentcamarche.net", "http://dmm.co.jp",
            "http://biglobe.ne.jp", "http://hdfcbank.com", "http://website-unavailable.com",
            "http://yandex.ua", "http://naukri.com", "http://ovh.net",
            "http://eastmoney.com", "http://jiayuan.com", "http://blogspot.ca",
            "http://swagbucks.com", "http://multiply.com", "http://agoda.com",
            "http://abril.com.br", "http://mpnrs.com", "http://spankwire.com",
            "http://livescore.com", "http://zillow.com", "http://google.fi",
            "http://engadget.com", "http://viadeo.com", "http://fotolia.com",
            "http://softpedia.com", "http://funmoods.com", "http://115.com",
            "http://clixsense.com", "http://avito.ru", "http://itau.com.br",
            "http://wix.com", "http://capitalone.com", "http://chip.de",
            "http://114so.cn", "http://hotfile.com", "http://cnblogs.com",
            "http://zanox.com", "http://blackhatworld.com", "http://jimdo.com",
            "http://verycd.com", "http://livingsocial.com", "http://verizonwireless.com",
            /*"http://sinaimg.cn",*/"http://quickmeme.com", "http://ebay.in",
            "http://youm7.com", "http://pch.com", "http://ibm.com",
            "http://888.com", "http://homedepot.com", "http://hypergames.net",
            "http://odesk.com", "http://123rf.com", "http://businessinsider.com",
            "http://meituan.com", "http://imesh.com", "http://zhaopin.com",
            "http://dangdang.com", "http://thesun.co.uk", "http://etao.com",
            "http://tabelog.com", "http://varzesh3.com", "http://kijiji.ca",
            /*"http://livedoor.biz",*/"http://webmd.com", "http://jquery.com",
            "http://alphaporno.com", "http://fotostrana.ru", "http://feedburner.com",
            "http://sitesell.com", "http://gc.ca", "http://hupu.com",
            /*"http://adjuggler.net",*/"http://neobux.com", "http://qunar.com",
            "http://mercadolibre.com.ar", "http://goodreads.com", "http://gutefrage.net",
            "http://as.com", "http://iminent.com", "http://marketwatch.com",
            "http://naver.jp", "http://lzjl.com", "http://gi-backoffice.com",
            "http://acesse.com", "http://retailmenot.com", "http://keezmovies.com",
            "http://discuz.net", "http://news.com.au",/*"http://demonoid.ph",*/
            "http://wikihow.com", "http://am10.ru", "http://issuu.com",
            "http://duowan.com", "http://persianblog.ir", "http://weather.com.cn",
            "http://people.com", "http://baixing.com", "http://linkbucks.com",
            "http://imagebam.com", "http://icicibank.com", "http://zing.vn",
            "http://adultadworld.com", "http://ya.ru", "http://virgilio.it",
            "http://microsoftonline.com", "http://sahibinden.com", "http://netlog.com",
            "http://wunderground.com", "http://linkbucksmedia.com", "http://macys.com",
            "http://189.cn", "http://sape.ru", "http://allrecipes.com",
            "http://foxsports.com", "http://lenta.ru", "http://miniclip.com",
            "http://quikr.com", "http://okwave.jp", "http://immobilienscout24.de",
            "http://exoclick.com", "http://beeg.com", "http://williamhill.com",
            "http://blog.163.com", "http://ustream.tv", "http://mobile.de",
            "http://oracle.com",/*"http://yomiuri.co.jp",*/"http://mapquest.com",
            "http://nu.nl", "http://folha.uol.com.br", "http://1channel.ch",
            "http://java.com", "http://exblog.jp", "http://who.is",
            "http://imagevenue.com", "http://xda-developers.com", "http://bleacherreport.com",
            "http://klout.com", "http://gotomeeting.com", "http://justin.tv",
            "http://accuweather.com", "http://time.com", "http://xtube.com",
            "http://shareasale.com", "http://cbsnews.com", "http://nuvid.com",
            "http://meilishuo.com", "http://monster.com", "http://gi-akademie.com",
            "http://lequipe.fr",/*"http://nokia.com",*/"http://mercadolibre.com.mx",
            "http://moneycontrol.com", "http://buzzfeed.com", "http://excite.co.jp",
            /*"http://linksynergy.com",*/"http://tradedoubler.com",/*"http://myegy.com",*/
            "http://xtendmedia.com", "http://bravotube.net", "http://www.net.cn",
            "http://sapo.pt", "http://pogo.com", "http://amung.us",
            "http://google.sk",/*"http://sears.com",*/"http://google.co.ma",
            "http://hc360.com", "http://rbc.ru", "http://slutload.com",
            "http://porn.com", "http://gamespot.com", "http://timeanddate.com",
            "http://yfrog.com", "http://pornhublive.com", "http://manta.com",
            "http://roulettebotplus.com", "http://ancestry.com", "http://backpage.com",
            "http://blackberry.com",/*"http://sponichi.co.jp",*/"http://pcgames.com.cn",
            "http://myfreecams.com", "http://slickdeals.net", "http://webmoney.ru",
            "http://livestrong.com", "http://force.com", "http://masrawy.com",
            "http://templatemonster.com",/*"http://twcczhu.com",*//*"http://blogspot.com.ar",*/
            /*"http://ocn.ne.jp",*/"http://tinypic.com", "http://nikkei.com",
            "http://taleo.net", "http://elance.com",/*"http://cocolog-nifty.com",*/
            "http://getresponse.com", "http://snapdeal.com", "http://21cn.com",
            "http://cnbc.com", "http://tutsplus.com", "http://wetter.com",
            "http://nhl.com", "http://china.com.cn", "http://gazzetta.it",
            "http://coupons.com", "http://wo.com.cn", "http://hotels.com",
            "http://cnbeta.com", "http://fatakat.com", "http://lady8844.com",
            "http://okcupid.com", "http://indianrail.gov.in", "http://namecheap.com",
            "http://zynga.com", "http://qidian.com", "http://trulia.com",
            "http://list-manage.com", "http://freakshare.com", "http://barnesandnoble.com",
            "http://justdial.com", "http://custhelp.com", "http://benaughty.com",
            "http://kickstarter.com", "http://gap.com", "http://way2sms.com",
            /*"http://cmbchina.com",*/"http://careerbuilder.com", "http://mangareader.net",
            "http://disney.go.com", "http://tnaflix.com", "http://smashingmagazine.com",
            "http://google.co.nz",/*"http://geocities.jp",*/"http://kinopoisk.ru",
            "http://zappos.com", "http://viddy.com",/*"http://cltrda.com",*/
            "http://nikkeibp.co.jp", "http://priceline.com", "http://codecanyon.net",
            "http://verizon.com", "http://intuit.com", "http://shopathome.com",
            "http://4tube.com", "http://skyrock.com", "http://lowes.com",
            "http://heise.de", "http://kayak.com",/*"http://52pk.net",*/
            "http://getfirebug.com", "http://ccb.com", "http://so-net.ne.jp",
            "http://wiktionary.org", "http://filehippo.com",/*"http://hlwan.net",*/
            "http://ndtv.com", "http://porntube.com", "http://sulekha.com",
            "http://bodybuilding.com", "http://cloob.com", "http://cracked.com",
            "http://icbc.com.cn", "http://quora.com", "http://babycenter.com",
            "http://yoka.com", "http://jabong.com", "http://interia.pl",
            /*"http://mybrowserbar.com",*//*"http://nhk.or.jp",*/"http://admagnet.net",
            "http://jxliu.com", "http://mtime.com", "http://blog.com",
            "http://lifehacker.com", "http://japanpost.jp", "http://google.az",
            "http://infolinks.com", "http://streamate.com", "http://hi5.com",
            "http://woot.com", "http://allocine.fr", "http://outlook.com",
            "http://tataindicom.com", "http://softlayer.com", "http://h2porn.com",
            "http://adscale.de", "http://aili.com", "http://mediaset.it",
            "http://clickbank.net", "http://southwest.com", "http://overstock.com",
            "http://dmoz.org", "http://pixnet.net", "http://mysql.com",
            "http://yellowpages.com", "http://bitshare.com", "http://cnr.cn",
            "http://gizmodo.com", "http://eluniversal.com.mx", "http://incredibar.com",
            "http://dict.cc", "http://pornerbros.com", "http://whitepages.com",
            "http://searchengines.ru",/*"http://tenpay.com",*//*"http://zx915.com",*/
            "http://usbank.com",/*"http://kohls.com",*/"http://v9.com",
            "http://last.fm", "http://td.com", "http://posterous.com",
            "http://magentocommerce.com", "http://subscene.com", "http://google.bg",
            "http://rottentomatoes.com",/*"http://blogimg.jp",*/"http://kompas.com",
            "http://dantri.com.vn", "http://beemp3.com", "http://seowhy.com",
            "http://6.cn", "http://hidemyass.com", "http://icontact.com",
            "http://stackexchange.com", "http://oneindia.in",/*"http://habrahabr.ru",*/
            "http://tubegalore.com", "http://pixiv.net", "http://howstuffworks.com",
            "http://1und1.de", "http://qip.ru", "http://semrush.com",
            "http://asos.com", "http://focus.cn", "http://linternaute.com",
            "http://tabnak.ir", "http://google.lk", "http://cbssports.com",
            /*"http://rakuten.ne.jp",*/"http://welt.de", "http://cbslocal.com",
            "http://tv-links.eu", "http://pclady.com.cn", "http://ucoz.com",
            "http://google.com.qa", "http://flippa.com", "http://yxlady.com",
            "http://dreamstime.com", "http://pcworld.com", "http://businessweek.com",
            "http://mp3skull.com", "http://logsoku.com", "http://google.com.kw",
            "http://rtl.de", "http://logmein.com", "http://realtor.com",
            "http://telegraaf.nl", "http://betfair.com", "http://empowernetwork.com",
            "http://ca.gov", "http://gismeteo.ru", "http://inbox.com",
            "http://wired.com", "http://xyxy.net", "http://nextag.com",
            "http://quibids.com", "http://theplanet.com", "http://nydailynews.com",
            "http://gumtree.com", "http://foursquare.com", "http://citibank.com",
            "http://aftonbladet.se", "http://adult-empire.com", "http://sfgate.com",
            "http://fileserve.com", "http://networkedblogs.com", "http://basecamphq.com",
            "http://yihaodian.com", "http://olx.in", "http://51cto.com",
            "http://pastebin.com", "http://makeuseof.com", "http://macrumors.com",
            "http://24h.com.vn", "http://trafficholder.com", "http://hsbc.co.uk",
            "http://haberturk.com", "http://7k7k.com", "http://hubspot.com",
            "http://google.com.do", "http://siteadvisor.com", "http://xdating.com",
            "http://sfr.fr", "http://paper.li", "http://idnes.cz",
            "http://onlinedown.net", "http://menepe.com", "http://vente-privee.com",
            "http://impress.co.jp", "http://mcssl.com", "http://zhubajie.com",
            "http://mercadolibre.com.ve", "http://popads.net", "http://eyny.com",
            /*"http://filesonic.com",*/"http://intel.com", "http://biglion.ru",
            "http://dpreview.com", "http://europa.eu", "http://marktplaats.nl",
            "http://ctrip.com", "http://urbandictionary.com",/*"http://klikbca.com",*/
            "http://ubuntu.com", "http://glispa.com", "http://4chan.org",
            "http://united.com", "http://alertpay.com", "http://largeporntube.com",
            "http://focus.de", "http://userapi.com", "http://rightmove.co.uk",
            "http://tom.com", "http://watchseries.eu", "http://jugem.jp",
            "http://xhamstercams.com", "http://51.com", "http://pagesjaunes.fr",
            "http://r7.com", "http://bigpoint.com",/*"http://asahi.com",*/
            "http://makemytrip.com", "http://google.com.ec", "http://suning.com",
            "http://foodnetwork.com", "http://orf.at", "http://sky.com",
            "http://anonym.to", "http://iteye.com", "http://slando.ru",
            "http://searchengineland.com", "http://clarin.com", "http://zendesk.com",
            "http://51buy.com", "http://subito.it", "http://npr.org",
            /*"http://nasa.gov",*/"http://19lou.com",/*"http://lanacion.com.ar",*/
            "http://examiner.com", "http://webmasterworld.com", "http://nipic.com",
            "http://ticketmaster.com", "http://nate.com", "http://kicker.de",
            "http://hiapk.com", "http://radikal.ru", "http://pcpop.com",
            "http://firstload.com", "http://msn.com.cn", "http://sitemeter.com",
            "http://grooveshark.com", "http://onlylady.com", "http://empflix.com",
            "http://box.com", "http://onlinesbi.com", "http://mogujie.com",
            "http://bahn.de", "http://boston.com", "http://smh.com.au",
            "http://gamefaqs.com", "http://goo.gl",/*"http://patch.com",*/
            "http://eastday.com", "http://ppstream.com", "http://ilmeteo.it",
            "http://marketgid.com", "http://skysports.com", "http://sanook.com",
            "http://avast.com", "http://motherless.com", "http://seobook.com",
            "http://tf1.fr", "http://ask.fm", "http://thechive.com",
            "http://ads8.com",/*"http://oron.com",*/"http://freeones.com",
            /*"http://blogspot.com.au",*/"http://gmw.cn", "http://novinky.cz",
            "http://20minutes.fr", "http://nordstrom.com", "http://eventbrite.com",
            "http://video-one.com",/*"http://idealbalans.com",*/"http://mail.com",
            /*"http://chinabroadcast.cn",*/"http://sueddeutsche.de", "http://sunporno.com",
            "http://traidnt.net", "http://1and1.com", "http://afimet.com",
            "http://nuomi.com", "http://programme-tv.net",/*"http://sanspo.com",*/
            "http://nfl.com",/*"http://itmedia.co.jp",*/"http://m-w.com",
            "http://thespecialsearch.com", "http://sdo.com", "http://break.com",
            "http://delta.com", "http://esporte.uol.com.br", "http://ebay.ca",
            "http://speedbit.com", "http://bhphotovideo.com",/*"http://earthlink.net",*/
            /*"http://cloudfront.net",*/"http://docin.com", "http://enterfactory.com",
            "http://opera.com", "http://brothersoft.com",/*"http://wansxd.com",*/
            "http://jeuxvideo.com", "http://meteofrance.com", "http://weblio.jp",
            "http://ft.com", "http://nike.com", "http://opensiteexplorer.org",
            "http://uefa.com", "http://google.com.ly", "http://dyndns.org",
            "http://nationalgeographic.com", "http://costco.com", "http://xbox.com",
            /*"http://bearshare.net"*/};

    public static final String[] topHttpsResources = {"https://us.etrade.com", "https://your-freedom.de", "https://github.com",
            "https://isocket.com", "https://plus.google.com", "https://paypal.com",
            /*"https://www.bigtopcupcake.com",*/"https://foursquare.com", "https://accounts.google.com",
            "https://mail.google.com", "https://plusone.google.com", "https://accounts.youtube.com",
            "https://login.live.com", "https://encrypted.google.com", "https://apps.facebook.com",
            "https://images-na.ssl-images-amazon.com", "https://docs.google.com", "https://service.gmx.net",
            "https://www.youtube.com", "https://www.google.co.uk", "https://www.amazon.com",
            "https://www.facebook.com", "https://accounts.youtube.com", "https://googleads.g.doubleclick.net",
            "https://cscentral.amazon.com", "https://addons.mozilla.org", "https://sites.fcps.org/essl",
            "https://thepiratebay.se", "https://www.accessnow.org/page/s/protectourprivacy", "https://wordpress.org",
            "https://www.eniro.se", "https://idg.se", "https://www.flashback.org",
            "https://cdon.se", "https://bankofamerica.com", "https://ims.nea.org/ims/login.action",
            "https://sites.google.com/site/cdnem8marta", "https://sites.google.com/site/mf2012theviper", "https://sites.fastspring.com/mobileways/instant/gravity",
            "https://httpsnow.org", "https://sites.aces.edu/Pages/Default.aspx", "https://sites.leedslearning.net/schools/horsforth/Pages/Index.aspx",
            "https://sites.secure.force.com/appexchange/home", "https://www.trustthecheck.com/#/trust_the_check"};
}
